<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.545">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Rapita Rani Br Pasaribu">
<meta name="dcterms.date" content="2024-01-25">

<title>Pengaruh Produksi Jagung Indonesia Terhadap Volume Ekspor Jagung Tahun 2013-2022</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Produksi Jagung Indonesia Terhadap Volume Ekspor Jagung Tahun 2013-2022</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Rapita Rani Br Pasaribu </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 25, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="poltekapp.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%"></p>
</figure>
</div>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Indonesia adalah salah satu negara yang dikenal sebagai negara agraris di dunia. Indonesia sudah terkenal akan produksi agrarisnya, terutama pada komoditas jagung. Jagung merupakan salah satu komoditas pertanian utama di Indonesia dan memiliki peran penting dalam perekonomian negara. Selain itu, jagung juga menjadi komoditas ekspor yang penting bagi Indonesia.</p>
<p>Penting untuk memahami bahwa jagung memiliki peran strategis dalam keberlanjutan sektor pertanian dan perekonomian nasional. Oleh karena itu, penelitian mengenai pengaruh produksi jagung terhadap volume ekspor jagung di Indonesia menjadi relevan untuk memahami dinamika pasar dan mencari strategi yang tepat untuk meningkatkan kontribusi jagung sebagai komoditas ekspor.</p>
<p>Penelitian ini akan mencoba mengeksplorasi hubungan antara produksi jagung di Indonesia dengan volume ekspor jagung. Produksi jagung yang tinggi seharusnya dapat menciptakan peluang untuk meningkatkan ekspor, tetapi faktor-faktor seperti kebijakan pemerintah, kualitas produk, dan persaingan global dapat mempengaruhi sejauh mana jagung Indonesia dapat mengekspansi pasar internasional.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Penulis mengambil objek penelitian yang akan digunakan sebagai variabel penelitian dari Data Badan Pusat Statistik dan Kementerian Pertanian. Penelitian ini berfokus pada analisis hubungan antara Produksi Jagung dan Volume Ekspor Indonesia tahun 2013-2022. Ruang lingkup penelitian ini mencakup data Volume Ekspor Jagung Indonesia serta Data Produksi Jagung selama sepuluh tahun.Variabel yang penulis gunakan adalah Volume Ekspor Jagung Indonesia sebagai Variabel Dependen dan Volume Produksi Jagung Indonesia sebagai Variabel Independen.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<p>Berdasarkan penjelasan tersebut maka pokok masalah penelitian ini adalah:</p>
<ol type="1">
<li>Apakah ada pengaruh signifikan antara Volume Produksi Jagung terhadap Volume Ekspor Jagung Indonesia tahun 2013-2022?</li>
<li>Bagaimana hubungan antara Volume Produksi Jagung terhadap Volume Ekspor Jagung Indonesia tahun 2013-2022?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Tujuan dari penelitian ini adalah untuk menganalisis hubungan antara Volume Produksi Jagung dan Volume Ekspor Jagung Indonesia. Dengan menggunakan metode uji regresi, penelitian ini bertujuan untuk menentukan sejauh mana produksi jagung mempengaruhi ekspor.</p>
<p>Adapun manfaat penelitian ini adalah:</p>
<ol type="1">
<li><p>Pengembangan Kebijakan: Hasil penelitian ini dapat memberikan dasar yang kuat untuk pengembangan kebijakan pertanian dan perdagangan yang mendukung pertumbuhan produksi jagung dan peningkatan volume ekspor. Pemerintah dapat menggunakan temuan ini untuk merancang kebijakan yang mendukung daya saing jagung Indonesia di pasar global.</p></li>
<li><p>Pemberdayaan Petani: Penelitian ini dapat memberikan informasi yang berguna kepada petani jagung, memungkinkan mereka untuk mengambil keputusan yang lebih baik terkait varietas yang akan ditanam, teknologi pertanian yang digunakan, dan strategi manajemen risiko. Peningkatan produksi dan ekspor jagung dapat memberikan dampak positif pada pendapatan petani.</p></li>
<li><p>Peningkatan Daya Saing: Dengan pemahaman yang lebih baik tentang faktor-faktor yang mempengaruhi volume ekspor jagung, pelaku industri dapat mengidentifikasi peluang untuk meningkatkan daya saing produk jagung Indonesia. Hal ini dapat mencakup peningkatan kualitas, diversifikasi produk, dan pengembangan strategi pemasaran yang lebih efektif.</p></li>
</ol>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'tidyverse'</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'readxl'</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'dplyr'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<ol type="1">
<li>Ekspor</li>
</ol>
<p>Ekspor merupakan proses perdagangan internasional yang dilakukan oleh individu, perusahaan, atau lembaga dengan tujuan untuk melakukan pertukaran barang antar negara. Definisi ini sejalan dengan ketentuan Undang-undang Kepabeanan Pasal 1 ayat 14, yang menyatakan bahwa pemerintah berupaya meningkatkan cadangan devisa melalui pengembangan arus ekspor. Oleh karena itu, pemerintah memberikan himbauan agar proses ekspor barang dari Indonesia dapat berjalan lancar tanpa harus melalui pemeriksaan fisik, kecuali jika ada kebutuhan tertentu untuk melakukan pemeriksaan barang ekspor (Pabean, 2017).</p>
<p>Selanjutnya, menurut Peraturan Pemerintah Republik Indonesia Nomor 2 tahun 2009, ekspor didefinisikan sebagai kegiatan pengeluaran barang dari daerah pabean. Daerah pabean mencakup wilayah Republik Indonesia, termasuk wilayah darat, perairan, dan ruang udara di atasnya, serta tempat-tempat tertentu di Zona Ekonomi Eksklusif dan landas kontinen. Seluruh proses ekspor harus mematuhi ketentuan dan peraturan yang berlaku sesuai dengan peraturan pemerintah.</p>
<ol start="2" type="1">
<li>Produksi</li>
</ol>
<p>Produksi adalah suatu proses untuk mengubah input menjadi output yang akan menambah nilai guna suatu barang. Menurut (Mubyarto, 1986) produksi merupakan hasil yang diperoleh petani dari hasil pengolahan atau pengelolaan usaha tani-nya, besar kecilnya keuntungan yang diperoleh petani diperhitungkan dari produksi.</p>
<p>Terdapat tiga aspek proses produksi antara lain :</p>
<ol type="1">
<li>Kuantitas barang atau jasa yang dihasilkan</li>
<li>Bentuk barang atau jasa diciptakan</li>
<li>Distribusi temporal dan spasial dari barang dan jasa yang dihasilkan</li>
</ol>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p>Berikut adalah data yang saya gunakan dalam penelitian ini, data berikut merupakan data Volume Ekspor Jagung Indonesia dan Produksi Jagung Indonesia tahun 2013-2022.</p>
<table class="table-hover table">
<caption>Produksi Jagung dan Volume Ekspor Jagung Indonesia (dalam ton)</caption>
<thead>
<tr class="header">
<th style="text-align: center;">TAHUN</th>
<th style="text-align: center;">PRODUKSI JAGUNG (Ton)</th>
<th style="text-align: center;">VOLUME EKSPOR JAGUNG (Ton)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">2013</td>
<td style="text-align: center;">21.903.00</td>
<td style="text-align: center;">11.418</td>
</tr>
<tr class="even">
<td style="text-align: center;">2014</td>
<td style="text-align: center;">19.008.000</td>
<td style="text-align: center;">37.889</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2015</td>
<td style="text-align: center;">19.612.000</td>
<td style="text-align: center;">250.831</td>
</tr>
<tr class="even">
<td style="text-align: center;">2016</td>
<td style="text-align: center;">23.578.000</td>
<td style="text-align: center;">41.875</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2017</td>
<td style="text-align: center;">27.950.000</td>
<td style="text-align: center;">47.002</td>
</tr>
<tr class="even">
<td style="text-align: center;">2018</td>
<td style="text-align: center;">30.560.000</td>
<td style="text-align: center;">341.523</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2019</td>
<td style="text-align: center;">22.590.000</td>
<td style="text-align: center;">53.566</td>
</tr>
<tr class="even">
<td style="text-align: center;">2020</td>
<td style="text-align: center;">24.050.000</td>
<td style="text-align: center;">64.272</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2021</td>
<td style="text-align: center;">23.040.000</td>
<td style="text-align: center;">2.539</td>
</tr>
<tr class="even">
<td style="text-align: center;">2022</td>
<td style="text-align: center;">23.100.000</td>
<td style="text-align: center;">162.033</td>
</tr>
</tbody>
</table>
<p>Sumber data: Kementerian Pertanian dan Badan Pusat Statistik Indonesia</p>
<p><img src="pertanian.png" class="img-fluid quarto-figure quarto-figure-left" style="width:35.0%" alt="Kementerian Pertanian."> <img src="bps.png" class="img-fluid quarto-figure quarto-figure-right" style="width:35.0%" alt="Logo BPS."></p>
<p>Berdasarkan data Badan Pusat Statistik (BPS), ekspor jagung di Indonesia mengalami peningkatan yang signifikan pada tahun 2022. Volume ekspor jagung pada tahun 2022 mencapai 162.033 ton, naik drastis dari tahun sebelumnya yang hanya 2.539 ton. Nilai ekspor jagung juga meningkat pesat, dari USD 0,77 juta menjadi USD 49,95 juta.</p>
<p>Peningkatan ekspor jagung ini disebabkan oleh beberapa faktor, antara lain:</p>
<ol type="1">
<li>Kenaikan harga jagung dunia, yang mendorong para eksportir Indonesia untuk meningkatkan produksi dan ekspornya.</li>
<li>Permintaan jagung yang tinggi dari beberapa negara tujuan ekspor, seperti Tiongkok, Vietnam, dan Filipina.</li>
<li>Pemerintah Indonesia yang memberikan subsidi kepada petani jagung, sehingga meningkatkan produktivitas dan produksi jagung.</li>
</ol>
<p>Peningkatan ekspor jagung ini memberikan dampak positif bagi perekonomian Indonesia, antara lain:</p>
<ol type="1">
<li>Meningkatkan pendapatan petani jagung dan pelaku usaha di sektor pertanian.</li>
<li>Meningkatkan devisa negara.</li>
<li>Memperkuat posisi Indonesia sebagai salah satu produsen jagung di dunia.</li>
</ol>
<p>Pada tahun 2023, ekspor jagung di Indonesia diperkirakan akan kembali mengalami peningkatan. Hal ini disebabkan oleh tingginya permintaan jagung dunia, serta adanya dukungan dari pemerintah untuk meningkatkan produksi jagung di Indonesia.</p>
</section>
<section id="import-data" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="import-data"><span class="header-section-number">3.2</span> Import Data</h3>
<p>Penelitian ini menggunakan data Volume Ekspor Jagung Indonesia sebagai Variabel Dependen dan Volume Produksi Jagung Indonesia sebagai Variabel Independen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Baca Data</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'readxl'</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Baca data</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"C:/Users/yusri/Documents/uasrp/jagung.xlsx"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  Tahun Produksi EksporJagung
  &lt;dbl&gt;    &lt;dbl&gt;        &lt;dbl&gt;
1  2013    21903         11.4
2  2014    19008         37.9
3  2015    19612        251. 
4  2016    23578         41.9
5  2017    27950         47.0
6  2018    30560        342. </code></pre>
</div>
</div>
</section>
<section id="plot" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="plot"><span class="header-section-number">3.3</span> Plot</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot Error</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(EksporJagung<span class="sc">~</span>Produksi,<span class="at">data=</span>dat)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Membuat Error</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>u<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot Error</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>EksporJagung,dat<span class="sc">$</span>u,<span class="at">xlab=</span><span class="st">"Produksi Jagung"</span>,<span class="at">ylab=</span><span class="st">"Ekspor Jagung"</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-mpg" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mpg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-mpg-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mpg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Plot Error Pengaruh Nilai Ekspor Tembakau terhadap PDB Indonesia
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot ggplot</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat, <span class="fu">aes</span>(<span class="at">x =</span> Produksi, <span class="at">y =</span> EksporJagung)) <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"gold"</span>,<span class="at">size=</span><span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Produksi Jagung"</span>, <span class="at">y =</span> <span class="st">"Volume Ekspor Jagung"</span>, </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Pengaruh Produksi Jagung Indonesia terhadap Volume Ekspor Jagung"</span>) <span class="sc">+</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-mpg2" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mpg2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-mpg2-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mpg2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Plot Pengaruh Produksi Jagung terhadap Volume Ekspor Indonesia
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.4</span> Metode analisis</h3>
<p>Metode yang dipilih adalah regresi univariat atau Ordinary Least Square (OLS) dengan 1 variabel independen. Penelitian ini bertujuan untuk mencari Pengaruh Produksi Jagung Indonesia terhadap Volume Ekspor Jagung. Spesifikasi yang dilakukan adalah:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah Volume Ekspor Jagung dan <span class="math inline">\(x_t\)</span> adalah Volume Produksi Jagung.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<p>Untuk menemukan hubungan antara Produksi Jagung dan Volume Ekspor Jagung Indonesia di tahun 2013-2022, saya menggunakan OLS Sehingga didapat hasil seperti tabel berikut:</p>
<table class="table-hover table">
<caption>Regresi Volume Produksi Jagung terhadap Volume Ekspor Jagung Indonesia</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: center;">Coefficient</th>
<th style="text-align: center;">Std. error</th>
<th style="text-align: center;">t-value</th>
<th style="text-align: center;">Prob(.)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: center;">-188.32840</td>
<td style="text-align: center;">253.59122</td>
<td style="text-align: center;">-0.743</td>
<td style="text-align: center;">0.479</td>
</tr>
<tr class="even">
<td style="text-align: left;">Produksi Jagung</td>
<td style="text-align: center;">0.01230</td>
<td style="text-align: center;">0.01067</td>
<td style="text-align: center;">1.153</td>
<td style="text-align: center;">0.282</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R Squared</td>
<td style="text-align: center;">0.1426</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Adjusted R Squared</td>
<td style="text-align: center;">0.03537</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">F Statistic</td>
<td style="text-align: center;">1.33</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Prob (F-Statistic)</td>
<td style="text-align: center;">0.2821</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<p>Hasil Regresi tersebut dimasukkan ke dalam rumus persamaan sehingga: <span class="math display">\[
y_{t}= -188.33 + 0.012X + \mu_t
\]</span> Dari persamaan tersebut, kita bisa menyimpulkan bahwa jika produksi Jagung Indonesia naik 1 ribu ton, Maka Volume Ekspor akan naik sebesar 0,012 ribu ton.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Model</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(EksporJagung<span class="sc">~</span>Produksi,<span class="at">data=</span>dat)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Interpretasi </span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = EksporJagung ~ Produksi, data = dat)

Residuals:
    Min      1Q  Median      3Q     Max 
-108.56  -67.28  -39.68   47.69  197.85 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)
(Intercept) -188.32840  253.59122  -0.743    0.479
Produksi       0.01230    0.01067   1.153    0.282

Residual standard error: 111.4 on 8 degrees of freedom
Multiple R-squared:  0.1426,    Adjusted R-squared:  0.03537 
F-statistic:  1.33 on 1 and 8 DF,  p-value: 0.2821</code></pre>
</div>
</div>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<ol type="1">
<li>Koefisien Regresi: Koefisien regresi untuk variabel Produksi adalah 0.01230. Ini berarti bahwa untuk setiap peningkatan satu unit dalam produksi jagung, kita dapat mengharapkan peningkatan sebesar 0.01230 unit dalam volume ekspor jagung, asumsi variabel lain tetap.</li>
<li>Signifikansi Statistik: Nilai p untuk variabel Produksi adalah 0.282, yang lebih besar dari ambang batas umum 0.05. Ini menunjukkan bahwa produksi jagung tidak memiliki pengaruh yang signifikan terhadap volume ekspor jagung di Indonesia pada tingkat kepercayaan 95%.</li>
<li>R-squared: Nilai R-squared adalah 0.1426, yang berarti bahwa model ini menjelaskan sekitar 14.26% variasi dalam volume ekspor jagung. Nilai ini cukup rendah, menunjukkan bahwa model ini mungkin tidak menjelaskan variasi dalam volume ekspor jagung dengan baik</li>
<li>Residuals: Residuals adalah perbedaan antara nilai yang diamati dan nilai yang diprediksi oleh model. Dalam hal ini, residuals berkisar antara -108.56 dan 197.85, menunjukkan bahwa model ini memiliki beberapa kesalahan prediksi yang cukup besar.</li>
</ol>
<p>Secara keseluruhan, hasil ini menunjukkan bahwa, berdasarkan data yang digunakan dalam analisis ini, produksi jagung tampaknya tidak memiliki pengaruh yang signifikan terhadap volume ekspor jagung di Indonesia. Namun, perlu diingat bahwa ini adalah hasil dari satu analisis dan mungkin perlu penelitian lebih lanjut untuk konfirmasi</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Adhi Susanto, S.P., M.Si., dan Dwi Setyowati, S.P., M.Si. (2023). “Jurnal Ilmiah Pertanian Tropika.” Potensi dan Strategi Peningkatan Ekspor Jagung Indonesia vol 22, No 1.</p>
<p>Kinastri, Rurry Garnish and , Ir. Maulidyah Indira Hasmarini, M.Si. (2019). Analisis Ekspor Jagung di Indonesia dan Faktor-Faktor Yang Mempengaruhinya.</p>
<p>M.S. Amir (2000). Ekspor Impor Teori dan Penerapannya. PPm. Jakarta. Hal 2.</p>
<p>Nurmayasari, Agus hudoyo dan Indah. 2019. PENINGKATAN PRODUKTIVITAS JAGUNG DI INDONESIA Vol 1, No 2.</p>
<p>Pusat Data dan Sistem Informasi Pertanian Sekretariat Jenderal Kementerian Pertanian (2020), Analisis Kinerja Perdagangan Jagung, 10(1b).</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>